name: GitHub Classroom Workflow
on: [push]

permissions:
  checks: write
  actions: write
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add your Python testing or feedback script execution here
      - name: Run Autograder
        run: |
          python3 .github/scripts/grading_script.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          ANY_REQUIRED_ENV_VAR: ${{ secrets.ANY_REQUIRED_ENV_VAR }}
        with:
          runners: autograder
